### Numpy Tutorial

- Numpy is a Python library for scientific computing with powerful tools for manipulating multi-dimensional arrays.
- A lot of Python packages use numpy functionality.
- Numpy performs the matrix manipulations internally using highly optimized C-code, which is often orders of magnitude faster than any implementation that one could write in pure python.
- Therefore, you should always think about how you can use numpy functionality and functions to replace your slow Python for-loops etc.
- If you use Python for scientific purposes, there is no way around numpy.

In this tutorial, we will go through some basic numpy functionality, but we cannot cover everything. For more advanced features, you can visit the [Numpy documentation](https://numpy.org/doc/stable/) or you can also ask [ChatGPT](https://chat.openai.com/) to rewrite some of your code using fast numpy features 😃.

#### Creating arrays

There are many ways to create multi-dimensional Numpy arrays. Here are a few examples how to create them from Python lists as well as 1s and 0s in a certrain shape. Most common libraries have functionalities to transform their datatypes into numpy arrays.

In [1]:
import numpy as np
np.set_printoptions(precision=2)

# From a Python list:
one_dim_array = np.array([1, 2, 3, 4, 5])
print("One dimensional array:\n", one_dim_array)

# From a Python list of lists:
two_dim_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Two dimensional array:\n", two_dim_array)

# Using built-in NumPy functions:
zeros_array = np.zeros((2, 3))  # creates a 2x3 array of zeros
print("Zeros array:\n", zeros_array)

ones_array = np.ones((2, 3))  # creates a 2x3 array of ones
print("Ones array:\n", ones_array)

One dimensional array:
 [1 2 3 4 5]
Two dimensional array:
 [[1 2 3]
 [4 5 6]]
Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]


#### Array shapes

Every numpy array has a "shape", which is a tuple of integers specifying the size of each dimension. This is an important information as the shape of an array determines, if it's compatible with another one to perform arithmetic operations. A numpy array can have an arbitrary number of dimensions, each with an arbitrary size.

The shape of a numpy array is fixed when it is created, you cannot add additional items to a dimension without creating a new array. This is different from Python lists, where you can add additional elements and make the list larger.

In [2]:
print("Shape of one dim array:\n", one_dim_array.shape) # shape (5,), can be interpreted as a vector with five entries
print("Shape of two dim array:\n", two_dim_array.shape) # shape (2,3), can be interpreted as a matrix with 2 rows and 3 columns

Shape of one dim array:
 (5,)
Shape of two dim array:
 (2, 3)


#### Array Indexing and Slicing

NumPy arrays can be indexed and sliced like Python lists with the index brackets `[]` and slice operator `:`. Additional functionality is added as each axis of the array can be indexed and sliced within the same brackets by addressing the nth axis at the nth index of the index brackets.

We can add an additional "dummy" dimension of size 1 to an existing array. For this, we can use `np.newaxis` when slicing the array or the `np.expand_dims()`-function. This is important to expand arrays into desired dimensionalities.

In [5]:
print("One dim array:\n", one_dim_array)
print("First element of one dim array:\n", one_dim_array[0])
print("Elements 2, 3, and 4 of one dim array:\n", one_dim_array[2:5])  # the final element of the slice is excluded
print("\n")

print("Two dim array:\n", two_dim_array)
print("Element at first axis 0, second axis 1:\n", two_dim_array[0, 1])
print("All Element at first axis and second axis 1 and up:\n", two_dim_array[:, 1:])
print("\n")

print("Array expansion")
print("Original shape:", one_dim_array.shape, "Expanded shape:", one_dim_array[:, np.newaxis].shape)
print("Original shape:", two_dim_array.shape, "Expanded shape:", np.expand_dims(two_dim_array, axis=2).shape)

One dim array:
 [1 2 3 4 5]
First element of one dim array:
 1
Elements 2, 3, and 4 of one dim array:
 [3 4 5]


Two dim array:
 [[1 2 3]
 [4 5 6]]
Element at first axis 0, second axis 1:
 2
All Element at first axis and second axis 1 and up:
 [[2 3]
 [5 6]]


Array expansion
Original shape: (5,) Expanded shape: (5, 1)
Original shape: (2, 3) Expanded shape: (2, 3, 1)


#### Numpy built-in functions and operations

NumPy arrays support many operations, including array reshaping, arithmetic operations, statistical operations, and linear algebra operations:


In [6]:
# Let's define some more arrays:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.arange(0, 6) # Return evenly spaced values within the given interval (default step size: 1)
c = np.zeros((3, 3))
print("a:\n", a)
print("b:\n", b)
print("c:\n", c)
print("\n")

# Arithmetic operations
print("Arithmetic operations")
print(f"a + b: {a + b}")
print(f"a - b: {a - b}")
print(f"a * b: {a * b}") # Multiplying two matrices / arrays is done element-wise! This is not matrix multiplication as known from math.
print(f"a / b: {a / b}")
print("\n")

# Logical operations
print("Logical operations")
# Returns a bool array of the same shape as "a", indicating for each element if a > 3 is True:
print(f"a > 3: {a > 3}")
# Another example:
print(f"b < 3: {b < 3}")
print("\n")

# Statistical operations
print("Statistical operations")
print(f"Mean of a: {np.mean(a)}")
print(f"Median of b: {np.median(b)}")
print(f"Standard deviation of a: {np.std(a)}")
print("\n")

# Flattening arrays
print("Flattening arrays")
print("Calling flatten() on an array flattens all dimensions into a single dimension")
print(c.flatten()) # Shape (9,)
print("\n")

# Reshaping operations
print("Reshaping operations")
print("'Reshape' first flattens the array (in our example, it is already flattened) and then turns it into the specified new shape.")
print("The total number of elements of the array remains the same, they are just spread differently across the dimensions.")
print(f"Reshaped b into 2x3 matrix:\n", b.reshape((2, 3)))


a:
 [1 2 3 4 5 6]
b:
 [0 1 2 3 4 5]
c:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Arithmetic operations
a + b: [ 1  3  5  7  9 11]
a - b: [1 1 1 1 1 1]
a * b: [ 0  2  6 12 20 30]
a / b: [ inf 2.   1.5  1.33 1.25 1.2 ]


Logical operations
a > 3: [False False False  True  True  True]
b < 3: [ True  True  True False False False]


Statistical operations
Mean of a: 3.5
Median of b: 2.5
Standard deviation of a: 1.707825127659933


Flattening arrays
Calling flatten() on an array flattens all dimensions into a single dimension
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


Reshaping operations
'Reshape' first flattens the array (in our example, it is already flattened) and then turns it into the specified new shape.
The total number of elements of the array remains the same, they are just spread differently across the dimensions.
Reshaped b into 2x3 matrix:
 [[0 1 2]
 [3 4 5]]


<ipython-input-6-5f58b9d3028c>:15: RuntimeWarning: divide by zero encountered in divide
  print(f"a / b: {a / b}")


### Broadcasting

One crucial and very powerful feature of numpy is broadcasting. This enables numpy to smartly change the shape of an array to make arithmetic operations between differently shaped arrays possible, as long as they are "broadcastable" into each other.

When adding or multiplying two arrays, they usually need to have the same shape to be able to apply the operation element-wise. Broadcasting allows operations such as addition or multiplication between arrays of different shapes, by duplicating ("broadcasting") the smaller array to match the larger array. This often makes it possible to vectorize array operations so that no slow Python loops are needed.

When operating on two arrays with different shapes, Numpy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimension and works its way left. Two dimensions are compatible if they are equal, or one of them is 1. If they are equal, then the dimensions are directly compatible and the operation can be performed element-wise as usual. If one of the dimensions is 1, then the array is duplicated along that dimension to match the size of the dimension of the other array.

Furthermore, the arrays do not need to have the same number of dimensions (length of the shapes do not have to be the same). If one of the arrays has a smaller number of dimensions, the missing dimensions are filled with "dummy" dimensions of size 1 from the left.

Let's look at some examples to make this clear:

In [7]:
print("Let's say we want to add a scalar value to a 2D array:")
h = np.array([[1, 2, 3], [4, 5, 6]])
i = 2
print(f"We add {i} to \n{h}\n and get \n{h + i}.")
print("The scalar value is broadcasted to each element of the array.\n")

print("Let's look at a more complicated example:")
j = np.array([1, 2, 3]) # shape (3,)
k = np.array([[1], [2]]) # shape (2,1)
print(f"We want to multiply \n{j}\n and \n{k}.")
print(f"The result is \n{j*k}.\n")

Let's say we want to add a scalar value to a 2D array:
We add 2 to 
[[1 2 3]
 [4 5 6]]
 and get 
[[3 4 5]
 [6 7 8]].
The scalar value is broadcasted to each element of the array.

Let's look at a more complicated example:
We want to multiply 
[1 2 3]
 and 
[[1]
 [2]].
The result is 
[[1 2 3]
 [2 4 6]].



Let's try to understand what is happening here in more detail.
The original shapes are (3,) and (2,1).
The shapes get aligned at the right side and than filled with ones to get the same number of dimensions: (1,3) * (2,1).
Then, as discussed above, dimensions of size 1 are duplicated / broadcasted to match the other array:
=> (2,3) * (2,3) after repeating each array along the 1-dimensions.

Now, the arrays have the same shapes and are being multiplied as usual, element-by-element.

Try to see if you can calculate the result of j*k yourself. Maybe you have to write it down.

In [8]:
print("Here is another example with a 2D matrix and a row vector and a column vector:")
matrix = np.array([[1,3],[3,5]]) # shape (2,2)
row_vector = np.array([2,1]) # shape (2,)
column_vector = np.array([[2],[1]]) # shape (1,2)
print("Matrix:\n", matrix)
print("Row vector:\n", row_vector)
print("Column vector:\n", column_vector)

print(f"In case of Matrix((2,2)) * row vector((2,)) the result is:\n {matrix*row_vector}")

print("""
Align the tensors at the right side and fill with 1s to match number
of dimensions: (2,2)*(1,2)
=> the vector is repeated ("broadcasted") along the rows of the matrix:
(2,2)*(2,2)
=> and then elementwise multiplication is applied as usual.
""")

print(f"In case of Matrix((2,2)) * column vector((1,2)) the result is:\n {matrix*column_vector}")
print("No dimensionality expansion is necessary, only repetion along the axis of length 1")

Here is another example with a 2D matrix and a row vector and a column vector:
Matrix:
 [[1 3]
 [3 5]]
Row vector:
 [2 1]
Column vector:
 [[2]
 [1]]
In case of Matrix((2,2)) * row vector((2,)) the result is:
 [[2 3]
 [6 5]]

Align the tensors at the right side and fill with 1s to match number 
of dimensions: (2,2)*(1,2) 
=> the vector is repeated ("broadcasted") along the rows of the matrix:
(2,2)*(2,2)
=> and then elementwise multiplication is applied as usual.

In case of Matrix((2,2)) * column vector((1,2)) the result is:
 [[2 6]
 [3 5]]
No dimensionality expansion is necessary, only repetion along the axis of length 1


Now, try playing around with multiplying or adding some arrays of your choice of different dimensions.

Try to understand, when the dimensions of two arrays are compatible and when not.

### Example: Computation of distance matrix between pairs of atoms

To showcase how powerful using broadcasting can be, we use a simple example. Given an array of 2D points (shape: (N,2)), we want to get the distance matrix D_ij that contains the distances between all pairs of points.

We start with a very inefficient implementation to compute this matrix using for-loops and python functionality.

In [9]:
import numpy as np

def get_distances_loop(coords):
  # Create an empty array for the result:
  distances = np.zeros((len(coords), len(coords)))

  # Fill the array:
  for i in range(len(coords)):
      for j in range(len(coords)):
          distances[i, j] = np.sqrt((coords[i][0] - coords[j][0]) ** 2 + (coords[i][1] - coords[j][1]) ** 2)

  return distances

# Create a list of coordinates
coords = [(0, 0), (1, 0), (1, 1)]

print(get_distances_loop(coords))

[[0.   1.   1.41]
 [1.   0.   1.  ]
 [1.41 1.   0.  ]]


Now, try to reimplement the computation of the distance matrix yourself using the broadcasting rules that we saw above. Here are some hints on how to do this:
- Create a numpy array from the python list `coords`
- Currently, this array has shape (N,2). Create two new arrays, one of shape (N,1,2) and one of shape (1,N,2). Use np.newaxis when indexing or np.expand_dims (see above) to achieve this. When these arrays are broadcasted to each other, then each coordinate will be repeated along each row or each column. When subtracted the coordinates on the diagonal will interact with themselves(results in 0) and interact with each other coordinate otherwise.
- Subtract these two arrays from each other. This will use broadcasting to get an array of shape (N,N,2) which contains the vector distance between each pair of atoms
- Use a combination of np.sqrt and np.sum to calculate the distance matrix of shape (N,N). Look up the documentation of np.sum if needed.

You can find the solution to this exercise at the very end of this notebook.

In [10]:
import numpy as np

def get_distances_numpy(coords):

  ### Your code goes here ###

  return None # Change this!

# Create a list of coordinates
coords = [(0, 0), (1, 0), (1, 1)]
print(get_distances_numpy(coords))

None


If you implemented it correctly, the numpy implementation should yield the same result as before.
We can compare the runtime of both approaches by passing a very large array into both functions:

In [11]:
import time

coords = np.random.randn(1000,2)

start = time.time()
loop_result = get_distances_loop(coords)
elapsed_loop = time.time()-start
print(f"Python loop implementation took {elapsed_loop}s")

start = time.time()
numpy_result = get_distances_numpy(coords)
elapsed_numpy = time.time()-start
if numpy_result is not None:
    print(f"Numpy implementation took {elapsed_numpy}s")

    results_are_equal = np.allclose(loop_result, numpy_result)

    if results_are_equal is True:
        print("The results from loop and numpy are the same.")
        print(f"Numpy was {elapsed_loop/elapsed_numpy} times faster then the python loop.")
    else:
        print("The result from loop and numpy are NOT the same.")
else:
    print("Implement the NumPy-Version first!")

Python loop implementation took 2.5932304859161377s
Implement the NumPy-Version first!


As you should see, the numpy-based implementation is a lot faster than the naive python implementation using for-loops.

### Solution

In [ ]:
## Solution to the distance matrix calculation:

import numpy as np

def get_distances_numpy(coords):

  # Convert the list of coordinates to a numpy array
  coords_array = np.array(coords)

  # Compute the distance matrix using broadcasting
  differences = coords_array[:, np.newaxis, :] - coords_array[np.newaxis, :, :] # (N,1,2)-(1,N,2) => resulting matrix will have shape (N,N,2), containing the vector distance between every pair of atoms
  distances = np.sqrt(np.sum(differences ** 2, axis=-1))

  return distances

# Create a list of coordinates
coords = [(0, 0), (1, 0), (1, 1)]
print(get_distances_numpy(coords))